// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: application_role.sql

package db

import (
	"context"
)

const getApplicationRoleByID = `-- name: GetApplicationRoleByID :one
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_application_role
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetApplicationRoleByID(ctx context.Context, id int32) (ShenApplicationRole, error) {
	row := q.db.QueryRow(ctx, getApplicationRoleByID, id)
	var i ShenApplicationRole
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getApplicationRoleByName = `-- name: GetApplicationRoleByName :one
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_application_role
WHERE
    name = $1
LIMIT 1
`

func (q *Queries) GetApplicationRoleByName(ctx context.Context, name string) (ShenApplicationRole, error) {
	row := q.db.QueryRow(ctx, getApplicationRoleByName, name)
	var i ShenApplicationRole
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApplicationRoles = `-- name: ListApplicationRoles :many
SELECT
    id,
    priority,
    name,
    created_at,
    updated_at
FROM
    shen_application_role
ORDER BY
    priority
`

func (q *Queries) ListApplicationRoles(ctx context.Context) ([]ShenApplicationRole, error) {
	rows, err := q.db.Query(ctx, listApplicationRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenApplicationRole
	for rows.Next() {
		var i ShenApplicationRole
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
