// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_application_role.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupApplicationRole = `-- name: AddGroupApplicationRole :one
INSERT INTO shen_group_application_role(group_id, application_id, role_id)
    VALUES ($1, $2, $3)
RETURNING
    id,
    group_id,
    application_id,
    role_id,
    created_at,
    updated_at
`

type AddGroupApplicationRoleParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
	RoleID        int32 `json:"role_id"`
}

func (q *Queries) AddGroupApplicationRole(ctx context.Context, arg AddGroupApplicationRoleParams) (ShenGroupApplicationRole, error) {
	row := q.db.QueryRow(ctx, addGroupApplicationRole, arg.GroupID, arg.ApplicationID, arg.RoleID)
	var i ShenGroupApplicationRole
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAllGroupApplicationRoles = `-- name: CountAllGroupApplicationRoles :one
SELECT
    COUNT(*)
FROM
    shen_group_application_role
`

func (q *Queries) CountAllGroupApplicationRoles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllGroupApplicationRoles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupApplicationRolesByApplication = `-- name: CountGroupApplicationRolesByApplication :one
SELECT
    COUNT(*)
FROM
    shen_group_application_role
WHERE
    application_id = $1
`

func (q *Queries) CountGroupApplicationRolesByApplication(ctx context.Context, applicationID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupApplicationRolesByApplication, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupApplicationRolesByGroup = `-- name: CountGroupApplicationRolesByGroup :one
SELECT
    COUNT(*)
FROM
    shen_group_application_role
WHERE
    group_id = $1
`

func (q *Queries) CountGroupApplicationRolesByGroup(ctx context.Context, groupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupApplicationRolesByGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllGroupApplicationRoles = `-- name: DeleteAllGroupApplicationRoles :exec
DELETE FROM shen_group_application_role
WHERE group_id = $1
    AND application_id = $2
`

type DeleteAllGroupApplicationRolesParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) DeleteAllGroupApplicationRoles(ctx context.Context, arg DeleteAllGroupApplicationRolesParams) error {
	_, err := q.db.Exec(ctx, deleteAllGroupApplicationRoles, arg.GroupID, arg.ApplicationID)
	return err
}

const deleteGroupApplicationRole = `-- name: DeleteGroupApplicationRole :exec
DELETE FROM shen_group_application_role
WHERE group_id = $1
    AND application_id = $2
    AND role_id = $3
`

type DeleteGroupApplicationRoleParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
	RoleID        int32 `json:"role_id"`
}

func (q *Queries) DeleteGroupApplicationRole(ctx context.Context, arg DeleteGroupApplicationRoleParams) error {
	_, err := q.db.Exec(ctx, deleteGroupApplicationRole, arg.GroupID, arg.ApplicationID, arg.RoleID)
	return err
}

const getGroupApplicationRole = `-- name: GetGroupApplicationRole :one
SELECT
    id,
    group_id,
    application_id,
    role_id,
    created_at,
    updated_at
FROM
    shen_group_application_role
WHERE
    group_id = $1
    AND application_id = $2
    AND role_id = $3
LIMIT 1
`

type GetGroupApplicationRoleParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
	RoleID        int32 `json:"role_id"`
}

func (q *Queries) GetGroupApplicationRole(ctx context.Context, arg GetGroupApplicationRoleParams) (ShenGroupApplicationRole, error) {
	row := q.db.QueryRow(ctx, getGroupApplicationRole, arg.GroupID, arg.ApplicationID, arg.RoleID)
	var i ShenGroupApplicationRole
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupApplicationRoleByID = `-- name: GetGroupApplicationRoleByID :one
SELECT
    id,
    group_id,
    application_id,
    role_id,
    created_at,
    updated_at
FROM
    shen_group_application_role
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetGroupApplicationRoleByID(ctx context.Context, id int32) (ShenGroupApplicationRole, error) {
	row := q.db.QueryRow(ctx, getGroupApplicationRoleByID, id)
	var i ShenGroupApplicationRole
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.RoleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserApplicationRoles = `-- name: GetUserApplicationRoles :many
SELECT DISTINCT
    r.id,
    r.priority,
    r.name,
    r.created_at,
    r.updated_at
FROM
    shen_group_application_role gar
    JOIN shen_user_group_member ugm ON gar.group_id = ugm.group_id
    JOIN shen_application_role r ON gar.role_id = r.id
WHERE
    ugm.user_id = $1
    AND gar.application_id = $2
ORDER BY
    r.priority DESC
`

type GetUserApplicationRolesParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) GetUserApplicationRoles(ctx context.Context, arg GetUserApplicationRolesParams) ([]ShenApplicationRole, error) {
	rows, err := q.db.Query(ctx, getUserApplicationRoles, arg.UserID, arg.ApplicationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenApplicationRole
	for rows.Next() {
		var i ShenApplicationRole
		if err := rows.Scan(
			&i.ID,
			&i.Priority,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT DISTINCT
    g.id,
    g.name,
    g.active,
    g.created_at,
    g.updated_at
FROM
    shen_user_group_member ugm
    JOIN shen_group g ON ugm.group_id = g.id
WHERE
    ugm.user_id = $1
    AND g.active = true
ORDER BY
    g.name
`

func (q *Queries) GetUserGroups(ctx context.Context, userID int32) ([]ShenGroup, error) {
	rows, err := q.db.Query(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenGroup
	for rows.Next() {
		var i ShenGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllGroupApplicationRoles = `-- name: ListAllGroupApplicationRoles :many
SELECT
    gar.id,
    g.name AS group_name,
    a.name AS application_name,
    r.name AS role_name,
    gar.created_at,
    gar.updated_at
FROM
    shen_group_application_role gar
    JOIN shen_application a ON gar.application_id = a.id
    JOIN shen_group g ON gar.group_id = g.id
    JOIN shen_application_role r ON gar.role_id = r.id
ORDER BY
    g.name,
    a.name,
    r.name
LIMIT $1 OFFSET $2
`

type ListAllGroupApplicationRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllGroupApplicationRolesRow struct {
	ID              int32              `json:"id"`
	GroupName       string             `json:"group_name"`
	ApplicationName string             `json:"application_name"`
	RoleName        string             `json:"role_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAllGroupApplicationRoles(ctx context.Context, arg ListAllGroupApplicationRolesParams) ([]ListAllGroupApplicationRolesRow, error) {
	rows, err := q.db.Query(ctx, listAllGroupApplicationRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupApplicationRolesRow
	for rows.Next() {
		var i ListAllGroupApplicationRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.ApplicationName,
			&i.RoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupApplicationRolesByApplication = `-- name: ListGroupApplicationRolesByApplication :many
SELECT
    gar.id,
    g.name AS group_name,
    r.name AS role_name,
    gar.created_at,
    gar.updated_at
FROM
    shen_group_application_role gar
    JOIN shen_group g ON gar.group_id = g.id
    JOIN shen_application_role r ON gar.role_id = r.id
WHERE
    gar.application_id = $1
ORDER BY
    g.name,
    r.name
LIMIT $2 OFFSET $3
`

type ListGroupApplicationRolesByApplicationParams struct {
	ApplicationID int32 `json:"application_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

type ListGroupApplicationRolesByApplicationRow struct {
	ID        int32              `json:"id"`
	GroupName string             `json:"group_name"`
	RoleName  string             `json:"role_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListGroupApplicationRolesByApplication(ctx context.Context, arg ListGroupApplicationRolesByApplicationParams) ([]ListGroupApplicationRolesByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listGroupApplicationRolesByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupApplicationRolesByApplicationRow
	for rows.Next() {
		var i ListGroupApplicationRolesByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.RoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupApplicationRolesByGroup = `-- name: ListGroupApplicationRolesByGroup :many
SELECT
    gar.id,
    a.name AS application_name,
    r.name AS role_name,
    gar.created_at,
    gar.updated_at
FROM
    shen_group_application_role gar
    JOIN shen_application a ON gar.application_id = a.id
    JOIN shen_application_role r ON gar.role_id = r.id
WHERE
    gar.group_id = $1
ORDER BY
    a.name,
    r.name
LIMIT $2 OFFSET $3
`

type ListGroupApplicationRolesByGroupParams struct {
	GroupID int32 `json:"group_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListGroupApplicationRolesByGroupRow struct {
	ID              int32              `json:"id"`
	ApplicationName string             `json:"application_name"`
	RoleName        string             `json:"role_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListGroupApplicationRolesByGroup(ctx context.Context, arg ListGroupApplicationRolesByGroupParams) ([]ListGroupApplicationRolesByGroupRow, error) {
	rows, err := q.db.Query(ctx, listGroupApplicationRolesByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupApplicationRolesByGroupRow
	for rows.Next() {
		var i ListGroupApplicationRolesByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationName,
			&i.RoleName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
