// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: group_applicaton_permission.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllGroupApplicationPermissions = `-- name: CountAllGroupApplicationPermissions :one
SELECT
    COUNT(*)
FROM
    shen_group_application_permission
`

func (q *Queries) CountAllGroupApplicationPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllGroupApplicationPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupApplicationPermissionsByApplication = `-- name: CountGroupApplicationPermissionsByApplication :one
SELECT
    COUNT(*)
FROM
    shen_group_application_permission
WHERE
    application_id = $1
`

func (q *Queries) CountGroupApplicationPermissionsByApplication(ctx context.Context, applicationID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupApplicationPermissionsByApplication, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGroupApplicationPermissionsByGroup = `-- name: CountGroupApplicationPermissionsByGroup :one
SELECT
    COUNT(*)
FROM
    shen_group_application_permission
WHERE
    group_id = $1
`

func (q *Queries) CountGroupApplicationPermissionsByGroup(ctx context.Context, groupID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countGroupApplicationPermissionsByGroup, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteGroupApplicationPermission = `-- name: DeleteGroupApplicationPermission :exec
DELETE FROM shen_group_application_permission
WHERE group_id = $1
    AND application_id = $2
`

type DeleteGroupApplicationPermissionParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) DeleteGroupApplicationPermission(ctx context.Context, arg DeleteGroupApplicationPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteGroupApplicationPermission, arg.GroupID, arg.ApplicationID)
	return err
}

const getGroupApplicationPermission = `-- name: GetGroupApplicationPermission :one
SELECT
    id,
    group_id,
    application_id,
    permission_id,
    created_at,
    updated_at
FROM
    shen_group_application_permission
WHERE
    group_id = $1
    AND application_id = $2
LIMIT 1
`

type GetGroupApplicationPermissionParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) GetGroupApplicationPermission(ctx context.Context, arg GetGroupApplicationPermissionParams) (ShenGroupApplicationPermission, error) {
	row := q.db.QueryRow(ctx, getGroupApplicationPermission, arg.GroupID, arg.ApplicationID)
	var i ShenGroupApplicationPermission
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupApplicationPermissionByID = `-- name: GetGroupApplicationPermissionByID :one
SELECT
    id,
    group_id,
    application_id,
    permission_id,
    created_at,
    updated_at
FROM
    shen_group_application_permission
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetGroupApplicationPermissionByID(ctx context.Context, id int32) (ShenGroupApplicationPermission, error) {
	row := q.db.QueryRow(ctx, getGroupApplicationPermissionByID, id)
	var i ShenGroupApplicationPermission
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserApplicationPermission = `-- name: GetUserApplicationPermission :one
SELECT
    p.id,
    p.priority,
    p.name,
    p.created_at,
    p.updated_at
FROM
    shen_group_application_permission gap
    JOIN shen_user_group_member ugm ON gap.group_id = ugm.group_id
    JOIN shen_permission p ON gap.permission_id = p.id
WHERE
    ugm.user_id = $1
    AND gap.application_id = $2
ORDER BY
    p.priority DESC
LIMIT 1
`

type GetUserApplicationPermissionParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) GetUserApplicationPermission(ctx context.Context, arg GetUserApplicationPermissionParams) (ShenPermission, error) {
	row := q.db.QueryRow(ctx, getUserApplicationPermission, arg.UserID, arg.ApplicationID)
	var i ShenPermission
	err := row.Scan(
		&i.ID,
		&i.Priority,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllGroupApplicationPermissions = `-- name: ListAllGroupApplicationPermissions :many
SELECT
    gap.id,
    g.name AS group_name,
    a.name AS application_name,
    p.name AS permission_name,
    gap.created_at,
    gap.updated_at
FROM
    shen_group_application_permission gap
    JOIN shen_application a ON gap.application_id = a.id
    JOIN shen_group g ON gap.group_id = g.id
    JOIN shen_permission p ON gap.permission_id = p.id
ORDER BY
    g.name,
    a.name,
    p.name
LIMIT $1 OFFSET $2
`

type ListAllGroupApplicationPermissionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllGroupApplicationPermissionsRow struct {
	ID              int32            `json:"id"`
	GroupName       string           `json:"group_name"`
	ApplicationName string           `json:"application_name"`
	PermissionName  string           `json:"permission_name"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListAllGroupApplicationPermissions(ctx context.Context, arg ListAllGroupApplicationPermissionsParams) ([]ListAllGroupApplicationPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listAllGroupApplicationPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllGroupApplicationPermissionsRow
	for rows.Next() {
		var i ListAllGroupApplicationPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.ApplicationName,
			&i.PermissionName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupApplicationPermissionsByApplication = `-- name: ListGroupApplicationPermissionsByApplication :many
SELECT
    gap.id,
    g.name AS group_name,
    p.name AS permission_name,
    gap.created_at,
    gap.updated_at
FROM
    shen_group_application_permission gap
    JOIN shen_group g ON gap.group_id = g.id
    JOIN shen_permission p ON gap.permission_id = p.id
WHERE
    gap.application_id = $1
ORDER BY
    g.name,
    p.name
LIMIT $2 OFFSET $3
`

type ListGroupApplicationPermissionsByApplicationParams struct {
	ApplicationID int32 `json:"application_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

type ListGroupApplicationPermissionsByApplicationRow struct {
	ID             int32            `json:"id"`
	GroupName      string           `json:"group_name"`
	PermissionName string           `json:"permission_name"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListGroupApplicationPermissionsByApplication(ctx context.Context, arg ListGroupApplicationPermissionsByApplicationParams) ([]ListGroupApplicationPermissionsByApplicationRow, error) {
	rows, err := q.db.Query(ctx, listGroupApplicationPermissionsByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupApplicationPermissionsByApplicationRow
	for rows.Next() {
		var i ListGroupApplicationPermissionsByApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.PermissionName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroupApplicationPermissionsByGroup = `-- name: ListGroupApplicationPermissionsByGroup :many
SELECT
    gap.id,
    a.name AS application_name,
    p.name AS permission_name,
    gap.created_at,
    gap.updated_at
FROM
    shen_group_application_permission gap
    JOIN shen_application a ON gap.application_id = a.id
    JOIN shen_permission p ON gap.permission_id = p.id
WHERE
    gap.group_id = $1
ORDER BY
    a.name,
    p.name
LIMIT $2 OFFSET $3
`

type ListGroupApplicationPermissionsByGroupParams struct {
	GroupID int32 `json:"group_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListGroupApplicationPermissionsByGroupRow struct {
	ID              int32            `json:"id"`
	ApplicationName string           `json:"application_name"`
	PermissionName  string           `json:"permission_name"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) ListGroupApplicationPermissionsByGroup(ctx context.Context, arg ListGroupApplicationPermissionsByGroupParams) ([]ListGroupApplicationPermissionsByGroupRow, error) {
	rows, err := q.db.Query(ctx, listGroupApplicationPermissionsByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupApplicationPermissionsByGroupRow
	for rows.Next() {
		var i ListGroupApplicationPermissionsByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationName,
			&i.PermissionName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setGroupApplicationPermission = `-- name: SetGroupApplicationPermission :one
INSERT INTO shen_group_application_permission(group_id, application_id, permission_id)
    VALUES ($1, $2, $3)
ON CONFLICT (group_id, application_id)
    DO UPDATE SET
        permission_id = EXCLUDED.permission_id
    RETURNING
        id,
        group_id,
        application_id,
        permission_id,
        created_at,
        updated_at
`

type SetGroupApplicationPermissionParams struct {
	GroupID       int32 `json:"group_id"`
	ApplicationID int32 `json:"application_id"`
	PermissionID  int32 `json:"permission_id"`
}

func (q *Queries) SetGroupApplicationPermission(ctx context.Context, arg SetGroupApplicationPermissionParams) (ShenGroupApplicationPermission, error) {
	row := q.db.QueryRow(ctx, setGroupApplicationPermission, arg.GroupID, arg.ApplicationID, arg.PermissionID)
	var i ShenGroupApplicationPermission
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.ApplicationID,
		&i.PermissionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
