// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jwt_keys.sql

package db

import (
	"context"
)

const countJWTKeys = `-- name: CountJWTKeys :one
SELECT
    COUNT(*)
FROM
    shen_jwt_keys
`

func (q *Queries) CountJWTKeys(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJWTKeys)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJWTKey = `-- name: CreateJWTKey :one
INSERT INTO shen_jwt_keys(kid, encrypted_private_key, public_key, active_for_signing, active_for_verification)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, kid, encrypted_private_key, public_key, created_at, active_for_signing, active_for_verification
`

type CreateJWTKeyParams struct {
	Kid                   string `json:"kid"`
	EncryptedPrivateKey   []byte `json:"encrypted_private_key"`
	PublicKey             string `json:"public_key"`
	ActiveForSigning      bool   `json:"active_for_signing"`
	ActiveForVerification bool   `json:"active_for_verification"`
}

func (q *Queries) CreateJWTKey(ctx context.Context, arg CreateJWTKeyParams) (ShenJwtKey, error) {
	row := q.db.QueryRow(ctx, createJWTKey,
		arg.Kid,
		arg.EncryptedPrivateKey,
		arg.PublicKey,
		arg.ActiveForSigning,
		arg.ActiveForVerification,
	)
	var i ShenJwtKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.EncryptedPrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
		&i.ActiveForSigning,
		&i.ActiveForVerification,
	)
	return i, err
}

const deactivateAllKeysForSigning = `-- name: DeactivateAllKeysForSigning :exec
UPDATE
    shen_jwt_keys
SET
    active_for_signing = FALSE
WHERE
    active_for_signing = TRUE
`

func (q *Queries) DeactivateAllKeysForSigning(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateAllKeysForSigning)
	return err
}

const deactivateKeyForSigning = `-- name: DeactivateKeyForSigning :exec
UPDATE
    shen_jwt_keys
SET
    active_for_signing = FALSE
WHERE
    id = $1
`

func (q *Queries) DeactivateKeyForSigning(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateKeyForSigning, id)
	return err
}

const deactivateKeyForVerification = `-- name: DeactivateKeyForVerification :exec
UPDATE
    shen_jwt_keys
SET
    active_for_verification = FALSE
WHERE
    id = $1
`

func (q *Queries) DeactivateKeyForVerification(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateKeyForVerification, id)
	return err
}

const deleteJWTKey = `-- name: DeleteJWTKey :exec
DELETE FROM shen_jwt_keys
WHERE id = $1
`

func (q *Queries) DeleteJWTKey(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteJWTKey, id)
	return err
}

const getActiveSigningKey = `-- name: GetActiveSigningKey :one
SELECT
    id,
    kid,
    encrypted_private_key,
    public_key,
    created_at,
    active_for_signing,
    active_for_verification
FROM
    shen_jwt_keys
WHERE
    active_for_signing = TRUE
LIMIT 1
`

func (q *Queries) GetActiveSigningKey(ctx context.Context) (ShenJwtKey, error) {
	row := q.db.QueryRow(ctx, getActiveSigningKey)
	var i ShenJwtKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.EncryptedPrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
		&i.ActiveForSigning,
		&i.ActiveForVerification,
	)
	return i, err
}

const getJWTKeyByID = `-- name: GetJWTKeyByID :one
SELECT
    id,
    kid,
    encrypted_private_key,
    public_key,
    created_at,
    active_for_signing,
    active_for_verification
FROM
    shen_jwt_keys
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetJWTKeyByID(ctx context.Context, id int32) (ShenJwtKey, error) {
	row := q.db.QueryRow(ctx, getJWTKeyByID, id)
	var i ShenJwtKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.EncryptedPrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
		&i.ActiveForSigning,
		&i.ActiveForVerification,
	)
	return i, err
}

const getJWTKeyByKID = `-- name: GetJWTKeyByKID :one
SELECT
    id,
    kid,
    encrypted_private_key,
    public_key,
    created_at,
    active_for_signing,
    active_for_verification
FROM
    shen_jwt_keys
WHERE
    kid = $1
LIMIT 1
`

func (q *Queries) GetJWTKeyByKID(ctx context.Context, kid string) (ShenJwtKey, error) {
	row := q.db.QueryRow(ctx, getJWTKeyByKID, kid)
	var i ShenJwtKey
	err := row.Scan(
		&i.ID,
		&i.Kid,
		&i.EncryptedPrivateKey,
		&i.PublicKey,
		&i.CreatedAt,
		&i.ActiveForSigning,
		&i.ActiveForVerification,
	)
	return i, err
}

const listActiveVerificationKeys = `-- name: ListActiveVerificationKeys :many
SELECT
    id,
    kid,
    encrypted_private_key,
    public_key,
    created_at,
    active_for_signing,
    active_for_verification
FROM
    shen_jwt_keys
WHERE
    active_for_verification = TRUE
ORDER BY
    created_at DESC,
    id DESC
`

func (q *Queries) ListActiveVerificationKeys(ctx context.Context) ([]ShenJwtKey, error) {
	rows, err := q.db.Query(ctx, listActiveVerificationKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenJwtKey
	for rows.Next() {
		var i ShenJwtKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.EncryptedPrivateKey,
			&i.PublicKey,
			&i.CreatedAt,
			&i.ActiveForSigning,
			&i.ActiveForVerification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJWTKeys = `-- name: ListJWTKeys :many
SELECT
    id,
    kid,
    encrypted_private_key,
    public_key,
    created_at,
    active_for_signing,
    active_for_verification
FROM
    shen_jwt_keys
WHERE
    ($2::text = '' OR kid < $2)
ORDER BY
    kid DESC
LIMIT $1
`

type ListJWTKeysParams struct {
	Limit     int32  `json:"limit"`
	CursorKid string `json:"cursor_kid"`
}

func (q *Queries) ListJWTKeys(ctx context.Context, arg ListJWTKeysParams) ([]ShenJwtKey, error) {
	rows, err := q.db.Query(ctx, listJWTKeys, arg.Limit, arg.CursorKid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenJwtKey
	for rows.Next() {
		var i ShenJwtKey
		if err := rows.Scan(
			&i.ID,
			&i.Kid,
			&i.EncryptedPrivateKey,
			&i.PublicKey,
			&i.CreatedAt,
			&i.ActiveForSigning,
			&i.ActiveForVerification,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
