// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShenApplication struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShenApplicationRole struct {
	ID        int32              `json:"id"`
	Priority  int32              `json:"priority"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShenGroup struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShenGroupApplicationRole struct {
	ID            int32              `json:"id"`
	GroupID       int32              `json:"group_id"`
	ApplicationID int32              `json:"application_id"`
	RoleID        int32              `json:"role_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ShenJwtKey struct {
	ID                    int32              `json:"id"`
	Kid                   string             `json:"kid"`
	EncryptedPrivateKey   []byte             `json:"encrypted_private_key"`
	PublicKey             string             `json:"public_key"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	ActiveForSigning      bool               `json:"active_for_signing"`
	ActiveForVerification bool               `json:"active_for_verification"`
}

type ShenSession struct {
	ID          int32              `json:"id"`
	HashedToken string             `json:"hashed_token"`
	UserID      int32              `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Revoked     bool               `json:"revoked"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type ShenToken struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	HashedToken   string             `json:"hashed_token"`
	UserID        int32              `json:"user_id"`
	ApplicationID int32              `json:"application_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Revoked       bool               `json:"revoked"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type ShenUser struct {
	ID             int32              `json:"id"`
	Username       string             `json:"username"`
	HashedPassword pgtype.Text        `json:"hashed_password"`
	Active         bool               `json:"active"`
	Role           int32              `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ShenUserGroupManager struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	GroupID   int32              `json:"group_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShenUserGroupMember struct {
	ID        int32              `json:"id"`
	UserID    int32              `json:"user_id"`
	GroupID   int32              `json:"group_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ShenUserRole struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
