// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ShenApplication struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Active    bool             `json:"active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ShenGroup struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Active    bool             `json:"active"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ShenGroupApplicationPermission struct {
	ID            int32            `json:"id"`
	GroupID       int32            `json:"group_id"`
	ApplicationID int32            `json:"application_id"`
	PermissionID  int32            `json:"permission_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type ShenPermission struct {
	ID        int32            `json:"id"`
	Priority  int32            `json:"priority"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ShenSession struct {
	ID        int32            `json:"id"`
	Token     string           `json:"token"`
	UserID    int32            `json:"user_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Revoked   bool             `json:"revoked"`
	RevokedAt pgtype.Timestamp `json:"revoked_at"`
}

type ShenToken struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Token         string           `json:"token"`
	UserID        int32            `json:"user_id"`
	ApplicationID int32            `json:"application_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	ExpiresAt     pgtype.Timestamp `json:"expires_at"`
	Revoked       bool             `json:"revoked"`
	RevokedAt     pgtype.Timestamp `json:"revoked_at"`
}

type ShenUser struct {
	ID             int32            `json:"id"`
	Username       string           `json:"username"`
	HashedPassword pgtype.Text      `json:"hashed_password"`
	Active         bool             `json:"active"`
	Role           int32            `json:"role"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

type ShenUserGroupManager struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	GroupID   int32            `json:"group_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ShenUserGroupMember struct {
	ID        int32            `json:"id"`
	UserID    int32            `json:"user_id"`
	GroupID   int32            `json:"group_id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type ShenUserRole struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
