// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role.sql

package db

import (
	"context"
)

const getRoleByID = `-- name: GetRoleByID :one
SELECT
    id,
    name,
    created_at,
    updated_at
FROM
    shen_user_role
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int32) (ShenUserRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i ShenUserRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRoleByName = `-- name: GetRoleByName :one
SELECT
    id,
    name,
    created_at,
    updated_at
FROM
    shen_user_role
WHERE
    name = $1
LIMIT 1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (ShenUserRole, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i ShenUserRole
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRoles = `-- name: ListRoles :many
SELECT
    id,
    name,
    created_at,
    updated_at
FROM
    shen_user_role
ORDER BY
    name
`

func (q *Queries) ListRoles(ctx context.Context) ([]ShenUserRole, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenUserRole
	for rows.Next() {
		var i ShenUserRole
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
