// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveSessions = `-- name: CountActiveSessions :one
SELECT
    COUNT(*)
FROM
    shen_session
WHERE
    revoked = FALSE
    AND expires_at > NOW()
`

func (q *Queries) CountActiveSessions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveSessionsByUser = `-- name: CountActiveSessionsByUser :one
SELECT
    COUNT(*)
FROM
    shen_session
WHERE
    user_id = $1
    AND revoked = FALSE
    AND expires_at > NOW()
`

func (q *Queries) CountActiveSessionsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSessionsByUser = `-- name: CountSessionsByUser :one
SELECT
    COUNT(*)
FROM
    shen_session
WHERE
    user_id = $1
`

func (q *Queries) CountSessionsByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO shen_session(hashed_token, user_id, expires_at)
    VALUES ($1, $2, $3)
RETURNING
    id, hashed_token, user_id, created_at, expires_at, revoked, revoked_at
`

type CreateSessionParams struct {
	HashedToken string             `json:"hashed_token"`
	UserID      int32              `json:"user_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (ShenSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.HashedToken, arg.UserID, arg.ExpiresAt)
	var i ShenSession
	err := row.Scan(
		&i.ID,
		&i.HashedToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM shen_session
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteRevokedSessions = `-- name: DeleteRevokedSessions :exec
DELETE FROM shen_session
WHERE revoked = TRUE
`

func (q *Queries) DeleteRevokedSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRevokedSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM shen_session
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSessionByHashedToken = `-- name: GetSessionByHashedToken :one
SELECT
    id,
    hashed_token,
    user_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_session
WHERE
    hashed_token = $1
LIMIT 1
`

func (q *Queries) GetSessionByHashedToken(ctx context.Context, hashedToken string) (ShenSession, error) {
	row := q.db.QueryRow(ctx, getSessionByHashedToken, hashedToken)
	var i ShenSession
	err := row.Scan(
		&i.ID,
		&i.HashedToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
    id,
    hashed_token,
    user_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_session
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int32) (ShenSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i ShenSession
	err := row.Scan(
		&i.ID,
		&i.HashedToken,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const isSessionValid = `-- name: IsSessionValid :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            shen_session
        WHERE
            hashed_token = $1
            AND revoked = FALSE
            AND expires_at > NOW())
`

func (q *Queries) IsSessionValid(ctx context.Context, hashedToken string) (bool, error) {
	row := q.db.QueryRow(ctx, isSessionValid, hashedToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT
    id,
    hashed_token,
    user_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM shen_session
WHERE
    revoked = FALSE
    AND expires_at > NOW()
    AND ($2 = 0 OR id > $2)
ORDER BY id ASC
LIMIT $1
`

type ListActiveSessionsParams struct {
	Limit    int32       `json:"limit"`
	CursorID interface{} `json:"cursor_id"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, arg ListActiveSessionsParams) ([]ShenSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, arg.Limit, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenSession
	for rows.Next() {
		var i ShenSession
		if err := rows.Scan(
			&i.ID,
			&i.HashedToken,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveSessionsByUser = `-- name: ListActiveSessionsByUser :many
SELECT
    id,
    hashed_token,
    user_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_session
WHERE
    user_id = $2
    AND revoked = FALSE
    AND expires_at > NOW()
    AND ($3 = 0 OR id > $3)
ORDER BY
    id ASC
LIMIT $1
`

type ListActiveSessionsByUserParams struct {
	Limit    int32       `json:"limit"`
	UserID   int32       `json:"user_id"`
	CursorID interface{} `json:"cursor_id"`
}

func (q *Queries) ListActiveSessionsByUser(ctx context.Context, arg ListActiveSessionsByUserParams) ([]ShenSession, error) {
	rows, err := q.db.Query(ctx, listActiveSessionsByUser, arg.Limit, arg.UserID, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenSession
	for rows.Next() {
		var i ShenSession
		if err := rows.Scan(
			&i.ID,
			&i.HashedToken,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT
    id,
    hashed_token,
    user_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_session
WHERE
    user_id = $2
    AND ($3 = 0 OR id > $3)
ORDER BY
    id ASC
LIMIT $1
`

type ListSessionsByUserParams struct {
	Limit    int32       `json:"limit"`
	UserID   int32       `json:"user_id"`
	CursorID interface{} `json:"cursor_id"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]ShenSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.Limit, arg.UserID, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenSession
	for rows.Next() {
		var i ShenSession
		if err := rows.Scan(
			&i.ID,
			&i.HashedToken,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE
    shen_session
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    user_id = $1
    AND revoked = FALSE
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE
    shen_session
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const revokeSessionByHashedToken = `-- name: RevokeSessionByHashedToken :exec
UPDATE
    shen_session
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    hashed_token = $1
`

func (q *Queries) RevokeSessionByHashedToken(ctx context.Context, hashedToken string) error {
	_, err := q.db.Exec(ctx, revokeSessionByHashedToken, hashedToken)
	return err
}
