// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTokensByUser = `-- name: CountActiveTokensByUser :one
SELECT
    COUNT(*)
FROM
    shen_token
WHERE
    user_id = $1
    AND revoked = FALSE
    AND expires_at > NOW()
`

func (q *Queries) CountActiveTokensByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokensByApplication = `-- name: CountTokensByApplication :one
SELECT
    COUNT(*)
FROM
    shen_token
WHERE
    application_id = $1
`

func (q *Queries) CountTokensByApplication(ctx context.Context, applicationID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByApplication, applicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokensByUser = `-- name: CountTokensByUser :one
SELECT
    COUNT(*)
FROM
    shen_token
WHERE
    user_id = $1
`

func (q *Queries) CountTokensByUser(ctx context.Context, userID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTokensByUserApplication = `-- name: CountTokensByUserApplication :one
SELECT
    COUNT(*)
FROM
    shen_token
WHERE
    user_id = $1
    AND application_id = $2
`

type CountTokensByUserApplicationParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) CountTokensByUserApplication(ctx context.Context, arg CountTokensByUserApplicationParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTokensByUserApplication, arg.UserID, arg.ApplicationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO shen_token(name, hashed_token, user_id, application_id, expires_at)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, name, hashed_token, user_id, application_id, created_at, expires_at, revoked, revoked_at
`

type CreateTokenParams struct {
	Name          string             `json:"name"`
	HashedToken   string             `json:"hashed_token"`
	UserID        int32              `json:"user_id"`
	ApplicationID int32              `json:"application_id"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (ShenToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.Name,
		arg.HashedToken,
		arg.UserID,
		arg.ApplicationID,
		arg.ExpiresAt,
	)
	var i ShenToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedToken,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM shen_token
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const deleteRevokedTokens = `-- name: DeleteRevokedTokens :exec
DELETE FROM shen_token
WHERE revoked = TRUE
`

func (q *Queries) DeleteRevokedTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRevokedTokens)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM shen_token
WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteToken, id)
	return err
}

const getTokenByHashedToken = `-- name: GetTokenByHashedToken :one
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    hashed_token = $1
LIMIT 1
`

func (q *Queries) GetTokenByHashedToken(ctx context.Context, hashedToken string) (ShenToken, error) {
	row := q.db.QueryRow(ctx, getTokenByHashedToken, hashedToken)
	var i ShenToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedToken,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetTokenByID(ctx context.Context, id int32) (ShenToken, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i ShenToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedToken,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const getTokenByUserApplicationName = `-- name: GetTokenByUserApplicationName :one
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    user_id = $1
    AND application_id = $2
    AND name = $3
LIMIT 1
`

type GetTokenByUserApplicationNameParams struct {
	UserID        int32  `json:"user_id"`
	ApplicationID int32  `json:"application_id"`
	Name          string `json:"name"`
}

func (q *Queries) GetTokenByUserApplicationName(ctx context.Context, arg GetTokenByUserApplicationNameParams) (ShenToken, error) {
	row := q.db.QueryRow(ctx, getTokenByUserApplicationName, arg.UserID, arg.ApplicationID, arg.Name)
	var i ShenToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HashedToken,
		&i.UserID,
		&i.ApplicationID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
	)
	return i, err
}

const isTokenValid = `-- name: IsTokenValid :one
SELECT
    EXISTS (
        SELECT
            1
        FROM
            shen_token
        WHERE
            hashed_token = $1
            AND revoked = FALSE
            AND expires_at > NOW())
`

func (q *Queries) IsTokenValid(ctx context.Context, hashedToken string) (bool, error) {
	row := q.db.QueryRow(ctx, isTokenValid, hashedToken)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveTokensByUser = `-- name: ListActiveTokensByUser :many
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    user_id = $1
    AND revoked = FALSE
    AND expires_at > NOW()
ORDER BY
    created_at DESC
LIMIT $2 OFFSET $3
`

type ListActiveTokensByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListActiveTokensByUser(ctx context.Context, arg ListActiveTokensByUserParams) ([]ShenToken, error) {
	rows, err := q.db.Query(ctx, listActiveTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenToken
	for rows.Next() {
		var i ShenToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTokensByUserApplication = `-- name: ListActiveTokensByUserApplication :many
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    user_id = $1
    AND application_id = $2
    AND revoked = FALSE
    AND expires_at > NOW()
ORDER BY
    created_at DESC
LIMIT $3 OFFSET $4
`

type ListActiveTokensByUserApplicationParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) ListActiveTokensByUserApplication(ctx context.Context, arg ListActiveTokensByUserApplicationParams) ([]ShenToken, error) {
	rows, err := q.db.Query(ctx, listActiveTokensByUserApplication,
		arg.UserID,
		arg.ApplicationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenToken
	for rows.Next() {
		var i ShenToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByApplication = `-- name: ListTokensByApplication :many
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    application_id = $1
ORDER BY
    created_at DESC
LIMIT $2 OFFSET $3
`

type ListTokensByApplicationParams struct {
	ApplicationID int32 `json:"application_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) ListTokensByApplication(ctx context.Context, arg ListTokensByApplicationParams) ([]ShenToken, error) {
	rows, err := q.db.Query(ctx, listTokensByApplication, arg.ApplicationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenToken
	for rows.Next() {
		var i ShenToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    user_id = $1
ORDER BY
    created_at DESC
LIMIT $2 OFFSET $3
`

type ListTokensByUserParams struct {
	UserID int32 `json:"user_id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTokensByUser(ctx context.Context, arg ListTokensByUserParams) ([]ShenToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenToken
	for rows.Next() {
		var i ShenToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTokensByUserApplication = `-- name: ListTokensByUserApplication :many
SELECT
    id,
    name,
    hashed_token,
    user_id,
    application_id,
    created_at,
    expires_at,
    revoked,
    revoked_at
FROM
    shen_token
WHERE
    user_id = $1
    AND application_id = $2
ORDER BY
    created_at DESC
LIMIT $3 OFFSET $4
`

type ListTokensByUserApplicationParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
	Limit         int32 `json:"limit"`
	Offset        int32 `json:"offset"`
}

func (q *Queries) ListTokensByUserApplication(ctx context.Context, arg ListTokensByUserApplicationParams) ([]ShenToken, error) {
	rows, err := q.db.Query(ctx, listTokensByUserApplication,
		arg.UserID,
		arg.ApplicationID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShenToken
	for rows.Next() {
		var i ShenToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HashedToken,
			&i.UserID,
			&i.ApplicationID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserApplicationTokens = `-- name: RevokeAllUserApplicationTokens :exec
UPDATE
    shen_token
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    user_id = $1
    AND application_id = $2
    AND revoked = FALSE
`

type RevokeAllUserApplicationTokensParams struct {
	UserID        int32 `json:"user_id"`
	ApplicationID int32 `json:"application_id"`
}

func (q *Queries) RevokeAllUserApplicationTokens(ctx context.Context, arg RevokeAllUserApplicationTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllUserApplicationTokens, arg.UserID, arg.ApplicationID)
	return err
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE
    shen_token
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    user_id = $1
    AND revoked = FALSE
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE
    shen_token
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    id = $1
`

func (q *Queries) RevokeToken(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, revokeToken, id)
	return err
}

const revokeTokenByHashedToken = `-- name: RevokeTokenByHashedToken :exec
UPDATE
    shen_token
SET
    revoked = TRUE,
    revoked_at = NOW()
WHERE
    hashed_token = $1
`

func (q *Queries) RevokeTokenByHashedToken(ctx context.Context, hashedToken string) error {
	_, err := q.db.Exec(ctx, revokeTokenByHashedToken, hashedToken)
	return err
}
