// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE
  shen_user
SET
  active = TRUE
WHERE
  id = $1
`

func (q *Queries) ActivateUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const checkUsernameExists = `-- name: CheckUsernameExists :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      shen_user
    WHERE
      username = $1)
`

func (q *Queries) CheckUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT
  COUNT(*)
FROM
  shen_user
WHERE
  active = TRUE
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT
  COUNT(*)
FROM
  shen_user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO shen_user(username, hashed_password, role)
  VALUES ($1, $2, $3)
RETURNING
  id, username, active, role, created_at, updated_at
`

type CreateUserParams struct {
	Username       string      `json:"username"`
	HashedPassword pgtype.Text `json:"hashed_password"`
	Role           int32       `json:"role"`
}

type CreateUserRow struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Active    bool               `json:"active"`
	Role      int32              `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.HashedPassword, arg.Role)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Active,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE
  shen_user
SET
  active = FALSE
WHERE
  id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM shen_user
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  id,
  username,
  hashed_password,
  active,
  ROLE,
  created_at,
  updated_at
FROM
  shen_user
WHERE
  id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int32) (ShenUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i ShenUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Active,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id,
  username,
  hashed_password,
  active,
  ROLE,
  created_at,
  updated_at
FROM
  shen_user
WHERE
  username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (ShenUser, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i ShenUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.HashedPassword,
		&i.Active,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT
  su.id,
  su.username,
  su.active,
  sur.name AS role,
  su.created_at,
  su.updated_at
FROM
  shen_user su
JOIN
  shen_user_role sur ON su.role = sur.id
WHERE
  su.active = TRUE
  AND ($1::text = '' OR su.username > $1)
ORDER BY
  su.username
LIMIT $2
`

type ListActiveUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

type ListActiveUsersRow struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Active    bool               `json:"active"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActiveUsers(ctx context.Context, arg ListActiveUsersParams) ([]ListActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, listActiveUsers, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveUsersRow
	for rows.Next() {
		var i ListActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Active,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
  id,
  username,
  active,
  ROLE,
  created_at,
  updated_at
FROM
  shen_user
WHERE
  ($1::text = '' OR username > $1)
ORDER BY
  username
LIMIT $2
`

type ListUsersParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

type ListUsersRow struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Active    bool               `json:"active"`
	Role      int32              `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Active,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByRole = `-- name: ListUsersByRole :many
SELECT
  id,
  username,
  active,
  ROLE,
  created_at,
  updated_at
FROM
  shen_user
WHERE
  ROLE = $1
  AND ($2::text = '' OR username > $2)
ORDER BY
  username
LIMIT $3
`

type ListUsersByRoleParams struct {
	Role    int32  `json:"role"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

type ListUsersByRoleRow struct {
	ID        int32              `json:"id"`
	Username  string             `json:"username"`
	Active    bool               `json:"active"`
	Role      int32              `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersByRole(ctx context.Context, arg ListUsersByRoleParams) ([]ListUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersByRole, arg.Role, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByRoleRow
	for rows.Next() {
		var i ListUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Active,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE
  shen_user
SET
  hashed_password = $2
WHERE
  id = $1
`

type UpdateUserPasswordParams struct {
	ID             int32       `json:"id"`
	HashedPassword pgtype.Text `json:"hashed_password"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.HashedPassword)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE
  shen_user
SET
  ROLE = $2
WHERE
  id = $1
`

type UpdateUserRoleParams struct {
	ID   int32 `json:"id"`
	Role int32 `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}
